# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Fortune.create(fortune: %s(Today it's up to you to create the peacefulness you long for.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(A friend asks only for your time not your money.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(If you refuse to accept anything but the best, you very often get it.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(A smile is your passport into the hearts of others.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(A good way to keep healthy is to eat more Chinese food.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Your high-minded principles spell success.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Hard work pays off in the future, laziness pays off now.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Change can hurt, but it leads a path to something better.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Enjoy the good luck a companion brings you.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(People are naturally attracted to you.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(A chance meeting opens new doors to success and friendship.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(You learn from your mistakes... You will learn a lot today.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(If you have something good in your life, don't let it go!), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(What ever you're goal is in life, embrace it visualize it, and for it will be yours.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Your shoes will make you happy today.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(You cannot love life until you live the life you love.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Be on the lookout for coming events; They cast their shadows beforehand.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Land is always on the mind of a flying bird.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(The man or woman you desire feels the same about you.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Meeting adversity well is the source of your strength.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(A dream you have will come true.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Our deeds determine us, as much as we determine our deeds.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(Never give up. You're not a failure if you don't give up.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(You will become great if you believe in yourself.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(There is no greater pleasure than seeing your loved ones prosper.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(You will marry your lover.), author: 'http://www.fortunecookiemessage.com/archive.php')
Fortune.create(fortune: %s(A very attractive person has a message for you.), author: 'http://www.fortunecookiemessage.com/archive.php')
