development:
  adapter: postgresql
  encoding: unicode
  database: sin_ar_sample_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: sin_ar_sample_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: sin_ar_sample_prod
  pool: 2
  username: your_username
  password: your_password
