development:
  adapter: postgresql
  encoding: unicode
  database: ar_demo_dev
  pool: 2
  
test:
  adapter: postgresql
  encoding: unicode
  database: ar_demo_test
  pool: 2
  
production:
  adapter: postgresql
  encoding: unicode
  database: ar_demo_prod
  pool: 2
  